-- Migration 032: Academic formatting engine support.
-- See: docs/ResearchOne - Work Order X.md
-- See: .cursor/rules/28-academic-formatting-engine.mdc
--
-- Adds two tables:
--   evidence_aliases — stable [E1]-style aliases per (report, citation)
--                      for Lossless Evidence Aliases (Rule 28 I-8).
--   report_exports   — async export job records with status + output URL.
--
-- Idempotent. IF NOT EXISTS throughout.

-- ============================================================
-- 1. evidence_aliases — Lossless Evidence Aliases (Rule 28 I-8)
-- ============================================================
CREATE TABLE IF NOT EXISTS evidence_aliases (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id       UUID NOT NULL,
  citation_id     UUID NOT NULL,
  -- Alias text — '[E1]', '[E2]', etc. Generated by evidenceAliaser.ts.
  alias           TEXT NOT NULL,
  -- Monotonic ordinal — 1, 2, 3 within a report. Used for sort and
  -- to regenerate aliases deterministically on re-export.
  ordinal         INTEGER NOT NULL,
  -- Snapshotted CSL-JSON at the moment of alias assignment. If the
  -- underlying source row is later edited, the alias keeps its
  -- original citation form — that's the "Lossless" in the name.
  csl_json        JSONB NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- A given (report, citation) pair gets at most one alias. Rule 28 I-8.
  UNIQUE (report_id, citation_id),
  -- A given (report, ordinal) is unique. Used to render in order.
  UNIQUE (report_id, ordinal)
);

CREATE INDEX IF NOT EXISTS idx_evidence_aliases_report
  ON evidence_aliases(report_id, ordinal);

-- FK constraints in DO blocks per Cursor rule 13 (deploy-skew).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'evidence_aliases_report_id_fkey'
  ) THEN
    ALTER TABLE evidence_aliases
      ADD CONSTRAINT evidence_aliases_report_id_fkey
      FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'evidence_aliases_citation_id_fkey'
  ) THEN
    ALTER TABLE evidence_aliases
      ADD CONSTRAINT evidence_aliases_citation_id_fkey
      FOREIGN KEY (citation_id) REFERENCES report_citations(id) ON DELETE CASCADE;
  END IF;
END $$;

COMMENT ON TABLE evidence_aliases IS
  'Lossless Evidence Aliases (Rule 28 I-8). Stable [E#] tags per report '
  'with snapshotted CSL-JSON so citation text is frozen at alias '
  'assignment time, surviving later source edits.';

-- ============================================================
-- 2. report_exports — async export job records
-- ============================================================
CREATE TABLE IF NOT EXISTS report_exports (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  report_id       UUID NOT NULL,
  user_id         TEXT,
  -- Validated against an enum at the API layer (Rule 28 I-9).
  -- Stored as TEXT here so future formats don't require a migration.
  format          TEXT NOT NULL,
  style           TEXT NOT NULL,
  -- 'queued' → 'running' → 'completed' | 'failed' | 'timed_out'
  status          TEXT NOT NULL DEFAULT 'queued',
  -- Optional URL where the rendered file can be retrieved. Populated
  -- on success. Format is implementation-specific (S3, local path,
  -- signed URL).
  output_url      TEXT,
  -- Size of the output in bytes — useful for analytics + rate
  -- limiting.
  output_bytes    BIGINT,
  -- Error classification on failure. Free-form but structured by
  -- pandocRunner.ts: 'pandoc_not_installed', 'timeout',
  -- 'pandoc_error', 'xelatex_error', 'validation_error'.
  error_class     TEXT,
  error_detail    TEXT,
  -- Subprocess wall-clock timing for analytics — does NOT include
  -- queue time.
  pandoc_duration_ms INTEGER,
  queued_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_report_exports_report
  ON report_exports(report_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_exports_user
  ON report_exports(user_id, created_at DESC) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_report_exports_status
  ON report_exports(status, queued_at) WHERE status IN ('queued', 'running');

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'report_exports_report_id_fkey'
  ) THEN
    ALTER TABLE report_exports
      ADD CONSTRAINT report_exports_report_id_fkey
      FOREIGN KEY (report_id) REFERENCES reports(id) ON DELETE CASCADE;
  END IF;
END $$;

COMMENT ON TABLE report_exports IS
  'Async export jobs. Driven by reportExportWorker.ts via BullMQ. '
  'Status transitions: queued -> running -> {completed|failed|timed_out}.';
